/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SlitsRouteImport } from './routes/slits'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as PlansRouteImport } from './routes/plans'
import { Route as PlannerRouteImport } from './routes/planner'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CombinationsRouteImport } from './routes/combinations'
import { Route as CoilsRouteImport } from './routes/coils'
import { Route as BulkLabRouteImport } from './routes/bulk-lab'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlansPlanIdRouteImport } from './routes/plans.$planId'
import { Route as PlansPlanIdLinesNewRouteImport } from './routes/plans.$planId.lines.new'
import { Route as PlansPlanIdLinesLineIdEditRouteImport } from './routes/plans.$planId.lines.$lineId.edit'

const SlitsRoute = SlitsRouteImport.update({
  id: '/slits',
  path: '/slits',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansRoute = PlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => rootRouteImport,
} as any)
const PlannerRoute = PlannerRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CombinationsRoute = CombinationsRouteImport.update({
  id: '/combinations',
  path: '/combinations',
  getParentRoute: () => rootRouteImport,
} as any)
const CoilsRoute = CoilsRouteImport.update({
  id: '/coils',
  path: '/coils',
  getParentRoute: () => rootRouteImport,
} as any)
const BulkLabRoute = BulkLabRouteImport.update({
  id: '/bulk-lab',
  path: '/bulk-lab',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansPlanIdRoute = PlansPlanIdRouteImport.update({
  id: '/$planId',
  path: '/$planId',
  getParentRoute: () => PlansRoute,
} as any)
const PlansPlanIdLinesNewRoute = PlansPlanIdLinesNewRouteImport.update({
  id: '/lines/new',
  path: '/lines/new',
  getParentRoute: () => PlansPlanIdRoute,
} as any)
const PlansPlanIdLinesLineIdEditRoute =
  PlansPlanIdLinesLineIdEditRouteImport.update({
    id: '/lines/$lineId/edit',
    path: '/lines/$lineId/edit',
    getParentRoute: () => PlansPlanIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/audit': typeof AuditRoute
  '/bulk-lab': typeof BulkLabRoute
  '/coils': typeof CoilsRoute
  '/combinations': typeof CombinationsRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/planner': typeof PlannerRoute
  '/plans': typeof PlansRouteWithChildren
  '/products': typeof ProductsRoute
  '/slits': typeof SlitsRoute
  '/plans/$planId': typeof PlansPlanIdRouteWithChildren
  '/plans/$planId/lines/new': typeof PlansPlanIdLinesNewRoute
  '/plans/$planId/lines/$lineId/edit': typeof PlansPlanIdLinesLineIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/audit': typeof AuditRoute
  '/bulk-lab': typeof BulkLabRoute
  '/coils': typeof CoilsRoute
  '/combinations': typeof CombinationsRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/planner': typeof PlannerRoute
  '/plans': typeof PlansRouteWithChildren
  '/products': typeof ProductsRoute
  '/slits': typeof SlitsRoute
  '/plans/$planId': typeof PlansPlanIdRouteWithChildren
  '/plans/$planId/lines/new': typeof PlansPlanIdLinesNewRoute
  '/plans/$planId/lines/$lineId/edit': typeof PlansPlanIdLinesLineIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/audit': typeof AuditRoute
  '/bulk-lab': typeof BulkLabRoute
  '/coils': typeof CoilsRoute
  '/combinations': typeof CombinationsRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/planner': typeof PlannerRoute
  '/plans': typeof PlansRouteWithChildren
  '/products': typeof ProductsRoute
  '/slits': typeof SlitsRoute
  '/plans/$planId': typeof PlansPlanIdRouteWithChildren
  '/plans/$planId/lines/new': typeof PlansPlanIdLinesNewRoute
  '/plans/$planId/lines/$lineId/edit': typeof PlansPlanIdLinesLineIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/audit'
    | '/bulk-lab'
    | '/coils'
    | '/combinations'
    | '/dashboard'
    | '/login'
    | '/planner'
    | '/plans'
    | '/products'
    | '/slits'
    | '/plans/$planId'
    | '/plans/$planId/lines/new'
    | '/plans/$planId/lines/$lineId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/audit'
    | '/bulk-lab'
    | '/coils'
    | '/combinations'
    | '/dashboard'
    | '/login'
    | '/planner'
    | '/plans'
    | '/products'
    | '/slits'
    | '/plans/$planId'
    | '/plans/$planId/lines/new'
    | '/plans/$planId/lines/$lineId/edit'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/audit'
    | '/bulk-lab'
    | '/coils'
    | '/combinations'
    | '/dashboard'
    | '/login'
    | '/planner'
    | '/plans'
    | '/products'
    | '/slits'
    | '/plans/$planId'
    | '/plans/$planId/lines/new'
    | '/plans/$planId/lines/$lineId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuditRoute: typeof AuditRoute
  BulkLabRoute: typeof BulkLabRoute
  CoilsRoute: typeof CoilsRoute
  CombinationsRoute: typeof CombinationsRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  PlannerRoute: typeof PlannerRoute
  PlansRoute: typeof PlansRouteWithChildren
  ProductsRoute: typeof ProductsRoute
  SlitsRoute: typeof SlitsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/slits': {
      id: '/slits'
      path: '/slits'
      fullPath: '/slits'
      preLoaderRoute: typeof SlitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans': {
      id: '/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof PlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planner': {
      id: '/planner'
      path: '/planner'
      fullPath: '/planner'
      preLoaderRoute: typeof PlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/combinations': {
      id: '/combinations'
      path: '/combinations'
      fullPath: '/combinations'
      preLoaderRoute: typeof CombinationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coils': {
      id: '/coils'
      path: '/coils'
      fullPath: '/coils'
      preLoaderRoute: typeof CoilsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bulk-lab': {
      id: '/bulk-lab'
      path: '/bulk-lab'
      fullPath: '/bulk-lab'
      preLoaderRoute: typeof BulkLabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans/$planId': {
      id: '/plans/$planId'
      path: '/$planId'
      fullPath: '/plans/$planId'
      preLoaderRoute: typeof PlansPlanIdRouteImport
      parentRoute: typeof PlansRoute
    }
    '/plans/$planId/lines/new': {
      id: '/plans/$planId/lines/new'
      path: '/lines/new'
      fullPath: '/plans/$planId/lines/new'
      preLoaderRoute: typeof PlansPlanIdLinesNewRouteImport
      parentRoute: typeof PlansPlanIdRoute
    }
    '/plans/$planId/lines/$lineId/edit': {
      id: '/plans/$planId/lines/$lineId/edit'
      path: '/lines/$lineId/edit'
      fullPath: '/plans/$planId/lines/$lineId/edit'
      preLoaderRoute: typeof PlansPlanIdLinesLineIdEditRouteImport
      parentRoute: typeof PlansPlanIdRoute
    }
  }
}

interface PlansPlanIdRouteChildren {
  PlansPlanIdLinesNewRoute: typeof PlansPlanIdLinesNewRoute
  PlansPlanIdLinesLineIdEditRoute: typeof PlansPlanIdLinesLineIdEditRoute
}

const PlansPlanIdRouteChildren: PlansPlanIdRouteChildren = {
  PlansPlanIdLinesNewRoute: PlansPlanIdLinesNewRoute,
  PlansPlanIdLinesLineIdEditRoute: PlansPlanIdLinesLineIdEditRoute,
}

const PlansPlanIdRouteWithChildren = PlansPlanIdRoute._addFileChildren(
  PlansPlanIdRouteChildren,
)

interface PlansRouteChildren {
  PlansPlanIdRoute: typeof PlansPlanIdRouteWithChildren
}

const PlansRouteChildren: PlansRouteChildren = {
  PlansPlanIdRoute: PlansPlanIdRouteWithChildren,
}

const PlansRouteWithChildren = PlansRoute._addFileChildren(PlansRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuditRoute: AuditRoute,
  BulkLabRoute: BulkLabRoute,
  CoilsRoute: CoilsRoute,
  CombinationsRoute: CombinationsRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  PlannerRoute: PlannerRoute,
  PlansRoute: PlansRouteWithChildren,
  ProductsRoute: ProductsRoute,
  SlitsRoute: SlitsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
